version: "3.8"
services:
  smb:
    env_file: ./.env
    build: 
      context: ./
      args:
        - USERNAME=$USERNAME
        - PASSWORD=$PASSWORD
    ports:
      - "445:445"
# volumes have been specified as per they are in the smb.conf file. You may modify them according to your personal config of the smb.conf
    volumes:
      - "$LOCATION/sivabalansm:/mnt/share/$USERNAME"
      - "$LOCATION/temp:/mnt/share/temp"
      - "$LOCATION/media:/mnt/share/media"




